version: '2'
services:
    web:
        build:
            context: ./
            dockerfile: web.docker
        volumes:
            - ../:/var/www
        ports:
            - "8025:80"
        links:
            - app
    app:
        build:
            context: ./
            dockerfile: app.docker
        volumes:
            - ../:/var/www
        links:
            - database
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=database"
    database:
        image: mariadb
        environment:
            - "MYSQL_ROOT_PASSWORD=pass"
            - "MYSQL_DATABASE=museo"
        ports:
            - "33061:3306"
        volumes:
            - ./data:/var/lib/mysql
